#define STR_OK F("\r\n<OK>")
#define STR_READY F("<READY>")

#define STR_ERROR F("<ERROR>")
#define STR_DIGITAL_DATA F("<D-DATA>")
#define STR_ANALOG_DATA F("<A-DATA>")
#define STR_ECHO_ON F("<ECHO_ON>")
#define STR_ECHO_OFF F("<ECHO_OFF>")

#define STR_STATUS F("<STATUS>")
#define STR_COMMAND_MODE F("<CMD_MOD>")
#define STR_MEASUREMENT_MODE F("<MEAS_MOD>")
#define STR_CONTINOUSOUT_MODE F("<CONT_MOD>")
#define STR_DATAREADY_MODE F("<DAT_READY_MOD>")
#define STR_ECHO_MODE F("<ECHO_MOD>")



#define STR_DEV_RESTARTED F("<DEVICE RESTARTED>")

#define STR_OUTPUTS_SET F("<OUTP SET>")
#define STR_ANALOG_IPUTS_SET F("<A_INP SET>")
#define STR_DIGITAL_IPUTS_SET F("<D_INP SET>")
#define STR_DO_MEASUREMENT_CONFIRM F("<DO_MEAS>")
#define STR_MEASUREMENT_DATA_READY F("<DAT_READY>")
#define STR_INFINITE_SEQUENCE F("<INF_SEQ>")
#define STR_STOP_SEQUENCE F("<STOP_SEQ>")
