/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JDAQ */
/*
* 
@file JDAQ.h
@author Terry Wright
@email tw567@cam.ac.uk


These functions map to the JDAQ Java class in STRIMM
Java_uk_co_strimm_services_JDAQ_GetCameraMapStatus

will map to:

Java.uk.co.strimm.services.JDAQ.GetCameraMapStatus(...)

*/


#ifndef _Included_JDAQ
#define _Included_JDAQ
#ifdef __cplusplus
extern "C" {
#endif

	//Camera Image File Map

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_GDITestWriteArray
	(JNIEnv* env, jobject, jint data_w, jint data_h, jshortArray data,
		jint numBins, jint numSeries, jstring seriesNames, jdouble xMin, jdouble xMax, jdoubleArray yValues);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_GDIWriteNumbersOntoArray
	(JNIEnv* env, jobject, jintArray nums);


	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_GetCameraMapStatus
	(JNIEnv* env, jobject);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_RegisterCameraForCameraMap
	(JNIEnv* env, jobject, jstring cameraSz, jint w, jint h, jint bitDepth, jint binning,
		jint numRect, jintArray rois_x, jintArray rois_y, jintArray rois_w, jintArray rois_h);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_StartCameraMap
	(JNIEnv* env, jobject);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_ShutdownCameraMap
	(JNIEnv* env, jobject);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_Add16BitImageDataCameraMap
	(JNIEnv* env, jobject, jstring cameraSz, jdouble fps, jdouble interval, jint w, jint h, jshortArray pix, jboolean bSave);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_Add8BitImageDataCameraMap
	(JNIEnv* env, jobject, jstring cameraSz, jdouble fps, jdouble interval, jint w, jint h, jbyteArray pix, jboolean bSave);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_AddARGBBitImageDataCameraMap
	(JNIEnv* env, jobject, jstring cameraSz, jdouble fps, jdouble interval, jint w, jint h, jbyteArray pix, jboolean bSave);

	// NIDAQ source

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_InitProtocol
	(JNIEnv* env, jobject, jstring csvProt, jstring szFolder, jboolean bCompound, jboolean bRepeat, jint deviceID, jdouble minV, jdouble maxV, jstring szDeviceName);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_SetStartTrigger
	(JNIEnv*, jobject, jboolean bStartTrigger, jint pFIx, jboolean bRisingEdge, jdouble timeoutSec);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_SetTimingMethod
	(JNIEnv*, jobject, jint timingMethod);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_RunNext
	(JNIEnv* env, jobject, jdoubleArray pTimes, jdoubleArray pAOData, jdoubleArray pAIData, jintArray pDOData, jintArray pDIData);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_GetBufferDimensions(JNIEnv* env, jobject, jintArray bufSizes);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_UpdateDOChannel
	(JNIEnv* env, jobject, jintArray pDOData, jint line);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_UpdateAOChannel
	(JNIEnv* env, jobject, jdoubleArray pAOData, jint channel);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_ShutdownProtocol
	(JNIEnv*, jobject);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_TerminateProtocol
	(JNIEnv*, jobject);

	

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_GetNextNumSamples(JNIEnv* env, jobject);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_GetNumberOfDataPoints(JNIEnv* env, jobject);

	JNIEXPORT jdouble JNICALL Java_uk_co_strimm_services_JDAQ_GetCurrentRunSampleTime(JNIEnv* env, jobject);

	JNIEXPORT jlong JNICALL Java_uk_co_strimm_services_JDAQ_GetNumberOfStages(JNIEnv* env, jobject);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_GetNumChannels(JNIEnv* env, jobject, jint type);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_GetChannelFromIndex(JNIEnv* env, jobject, jint type, jint ix);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_GetPort(JNIEnv* env, jobject, jboolean bIn);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_GetDeviceID(JNIEnv* env, jobject);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_GetNextNumSamples(JNIEnv*, jobject);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_GetNumberOfDataPoints(JNIEnv*, jobject);

	JNIEXPORT jdouble JNICALL Java_uk_co_strimm_services_JDAQ_GetCurrentRunStartTime(JNIEnv*, jobject);

	JNIEXPORT jdouble JNICALL Java_uk_co_strimm_services_JDAQ_GetCurrentRunEndTime(JNIEnv*, jobject);

	JNIEXPORT jdouble JNICALL Java_uk_co_strimm_services_JDAQ_GetCurrentRunSampleTime(JNIEnv*, jobject);

	JNIEXPORT jlong JNICALL Java_uk_co_strimm_services_JDAQ_GetNumberOfStages(JNIEnv*, jobject);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_GetNumChannels(JNIEnv*, jobject, jint type);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_GetChannelFromIndex(JNIEnv*, jobject, jint type, jint ix);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_GetPort(JNIEnv*, jobject, jboolean bIn);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_GetDeviceID(JNIEnv*, jobject);

	//Useful Windows API functions

	JNIEXPORT jboolean JNICALL Java_uk_co_strimm_services_JDAQ_GetKeyState(JNIEnv*, jobject, int VK);

	JNIEXPORT jdouble JNICALL Java_uk_co_strimm_services_JDAQ_GetCurrentSystemTime(JNIEnv*, jobject);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_WinInitSpeechEngine(JNIEnv* env, jobject);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_WinShutdownSpeechEngine(JNIEnv* env, jobject);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_WinSpeak(JNIEnv* env, jobject, jstring outSz1, jboolean bSychronous);

	JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_WinBeep(JNIEnv* env, jobject, jint freq, jint dur);


#ifdef __cplusplus
}
#endif
#endif

