/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_strimm_services_JDAQ */

#ifndef _Included_uk_co_strimm_services_JDAQ
#define _Included_uk_co_strimm_services_JDAQ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_strimm_services_JDAQ
 * Method:    AddProtocol
 * Signature: (IDDDIZZZLjava/lang/String;Ljava/lang/String;[Z)I
 */
JNIEXPORT jint JNICALL Java_uk_co_strimm_services_JDAQ_AddProtocol
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble, jint, jboolean, jboolean, jboolean, jstring, jstring, jbooleanArray);

/*
 * Class:     uk_co_strimm_services_JDAQ
 * Method:    RemoveProtocol
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_uk_co_strimm_services_JDAQ_RemoveProtocol
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_co_strimm_services_JDAQ
 * Method:    InitDAQ
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_uk_co_strimm_services_JDAQ_InitDAQ
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_co_strimm_services_JDAQ
 * Method:    RunProtocol
 * Signature: ([D)Z
 */
JNIEXPORT jboolean JNICALL Java_uk_co_strimm_services_JDAQ_RunProtocol
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     uk_co_strimm_services_JDAQ
 * Method:    ShutdownDAQ
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_uk_co_strimm_services_JDAQ_ShutdownDAQ
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
