/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main____inlined__use__lambda__1 */

#ifndef _Included_main____inlined__use__lambda__1
#define _Included_main____inlined__use__lambda__1
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
