/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main__13__1 */

#ifndef _Included_main__13__1
#define _Included_main__13__1
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
