/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_strimm_NumericTimerProperty */

#ifndef _Included_uk_co_strimm_NumericTimerProperty
#define _Included_uk_co_strimm_NumericTimerProperty
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_strimm_NumericTimerProperty
 * Method:    getMax
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_uk_co_strimm_NumericTimerProperty_getMax
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_strimm_NumericTimerProperty
 * Method:    setMax
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_uk_co_strimm_NumericTimerProperty_setMax
  (JNIEnv *, jobject, jobject);

/*
 * Class:     uk_co_strimm_NumericTimerProperty
 * Method:    getMin
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_uk_co_strimm_NumericTimerProperty_getMin
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_strimm_NumericTimerProperty
 * Method:    setMin
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_uk_co_strimm_NumericTimerProperty_setMin
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
