/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_strimm_AbstractTimerProperty */

#ifndef _Included_uk_co_strimm_AbstractTimerProperty
#define _Included_uk_co_strimm_AbstractTimerProperty
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_strimm_AbstractTimerProperty
 * Method:    getValue
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_uk_co_strimm_AbstractTimerProperty_getValue
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_strimm_AbstractTimerProperty
 * Method:    setValue
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_uk_co_strimm_AbstractTimerProperty_setValue
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
