/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_strimm_ChannelType */

#ifndef _Included_uk_co_strimm_ChannelType
#define _Included_uk_co_strimm_ChannelType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
