/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_strimm_STRIMM_JNI */

#ifndef _Included_uk_co_strimm_STRIMM_JNI
#define _Included_uk_co_strimm_STRIMM_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_strimm_STRIMM_JNI
 * Method:    initialise
 * Signature: ()Luk/co/strimm/TimerResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_strimm_STRIMM_1JNI_initialise
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_strimm_STRIMM_JNI
 * Method:    deinitialise
 * Signature: ()Luk/co/strimm/TimerResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_strimm_STRIMM_1JNI_deinitialise
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_strimm_STRIMM_JNI
 * Method:    getInstalledDevicesEXT
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_uk_co_strimm_STRIMM_1JNI_getInstalledDevicesEXT
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_strimm_STRIMM_JNI
 * Method:    addInstallDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_co_strimm_STRIMM_1JNI_addInstallDirectory
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_co_strimm_STRIMM_JNI
 * Method:    createTimer
 * Signature: (Ljava/lang/String;)Luk/co/strimm/Timer;
 */
JNIEXPORT jobject JNICALL Java_uk_co_strimm_STRIMM_1JNI_createTimer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_co_strimm_STRIMM_JNI
 * Method:    deleteTimer
 * Signature: (Luk/co/strimm/Timer;)V
 */
JNIEXPORT void JNICALL Java_uk_co_strimm_STRIMM_1JNI_deleteTimer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     uk_co_strimm_STRIMM_JNI
 * Method:    getLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_co_strimm_STRIMM_1JNI_getLastError
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
