/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_strimm_TimerProperty */

#ifndef _Included_uk_co_strimm_TimerProperty
#define _Included_uk_co_strimm_TimerProperty
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_strimm_TimerProperty
 * Method:    getPropertyType
 * Signature: ()Luk/co/strimm/PropertyType;
 */
JNIEXPORT jobject JNICALL Java_uk_co_strimm_TimerProperty_getPropertyType
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_strimm_TimerProperty
 * Method:    isPreInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_uk_co_strimm_TimerProperty_isPreInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
