/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_strimm_Timer */

#ifndef _Included_uk_co_strimm_Timer
#define _Included_uk_co_strimm_Timer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_strimm_Timer
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_co_strimm_Timer_getName
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_strimm_Timer
 * Method:    getAPIVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_co_strimm_Timer_getAPIVersion
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_strimm_Timer
 * Method:    getLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_co_strimm_Timer_getLastError
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_strimm_Timer
 * Method:    initialiseEXT
 * Signature: ()Luk/co/strimm/TimerResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_strimm_Timer_initialiseEXT
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_strimm_Timer
 * Method:    getAvailableChannelsEXT
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_uk_co_strimm_Timer_getAvailableChannelsEXT
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_co_strimm_Timer
 * Method:    getChannelsEXT
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_uk_co_strimm_Timer_getChannelsEXT
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_co_strimm_Timer
 * Method:    addAnalogueInputEXT
 * Signature: (Ljava/lang/String;IDDLuk/co/strimm/STRIMM_JArrayCallback;)Luk/co/strimm/TimerResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_strimm_Timer_addAnalogueInputEXT
  (JNIEnv *, jobject, jstring, jint, jdouble, jdouble, jobject);

/*
 * Class:     uk_co_strimm_Timer
 * Method:    addAnalogueOutputEXT
 * Signature: (Ljava/lang/String;I[D)Luk/co/strimm/TimerResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_strimm_Timer_addAnalogueOutputEXT
  (JNIEnv *, jobject, jstring, jint, jdoubleArray);

/*
 * Class:     uk_co_strimm_Timer
 * Method:    addDigitalInputEXT
 * Signature: (Ljava/lang/String;ILuk/co/strimm/STRIMM_JArrayCallback;)Luk/co/strimm/TimerResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_strimm_Timer_addDigitalInputEXT
  (JNIEnv *, jobject, jstring, jint, jobject);

/*
 * Class:     uk_co_strimm_Timer
 * Method:    addDigitalOutputEXT
 * Signature: (Ljava/lang/String;I[B)Luk/co/strimm/TimerResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_strimm_Timer_addDigitalOutputEXT
  (JNIEnv *, jobject, jstring, jint, jbyteArray);

/*
 * Class:     uk_co_strimm_Timer
 * Method:    registerStopCallback
 * Signature: (Luk/co/strimm/STRIMM_JVoidCallback;)V
 */
JNIEXPORT void JNICALL Java_uk_co_strimm_Timer_registerStopCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     uk_co_strimm_Timer
 * Method:    registerErrorCallback
 * Signature: (Luk/co/strimm/STRIMM_JVoidCallback;)V
 */
JNIEXPORT void JNICALL Java_uk_co_strimm_Timer_registerErrorCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     uk_co_strimm_Timer
 * Method:    prime
 * Signature: ()Luk/co/strimm/TimerResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_strimm_Timer_prime
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_strimm_Timer
 * Method:    start
 * Signature: ()Luk/co/strimm/TimerResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_strimm_Timer_start
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_strimm_Timer
 * Method:    stop
 * Signature: ()Luk/co/strimm/TimerResult;
 */
JNIEXPORT jobject JNICALL Java_uk_co_strimm_Timer_stop
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_strimm_Timer
 * Method:    getPropertyNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_uk_co_strimm_Timer_getPropertyNames
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_strimm_Timer
 * Method:    getProperty
 * Signature: (Ljava/lang/String;)Luk/co/strimm/TimerProperty;
 */
JNIEXPORT jobject JNICALL Java_uk_co_strimm_Timer_getProperty
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_co_strimm_Timer
 * Method:    releaseProperty
 * Signature: (Luk/co/strimm/TimerProperty;)V
 */
JNIEXPORT void JNICALL Java_uk_co_strimm_Timer_releaseProperty
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
