/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_strimm_StringTimerProperty */

#ifndef _Included_uk_co_strimm_StringTimerProperty
#define _Included_uk_co_strimm_StringTimerProperty
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_strimm_StringTimerProperty
 * Method:    getAllowedValues
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_uk_co_strimm_StringTimerProperty_getAllowedValues
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
