/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_strimm_PropertyType */

#ifndef _Included_uk_co_strimm_PropertyType
#define _Included_uk_co_strimm_PropertyType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
