/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_strimm_STRIMM_JArrayCallback */

#ifndef _Included_uk_co_strimm_STRIMM_JArrayCallback
#define _Included_uk_co_strimm_STRIMM_JArrayCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
